services:
  - type: web
    name: backend-api
    env: node
    buildCommand: echo "No build needed - standalone server will install dependencies at runtime"
    startCommand: cd Backend && node standalone.js
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: DB_HOST
        value: 153.92.15.31
      - key: DB_PORT
        value: 3306
      - key: DB_USER
        value: u875409848_gaceta
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        value: u875409848_gaceta
    autoDeploy: true 